Map<int, String> perguntas = {
  1: "Gosto de organizar ideias, pessoas, recursos e tempo para um projeto a fim de ser mais eficiente.",
  2: "Prefiro ser líder quando estou num grupo.",
  3: "Tenho facilidade em descobrir novos ensinamentos na Bíblia.",
  4: "Consigo detectar quando uma pessoa está com problemas emocionais, e sinto o desejo de ajudá-la.",
  5: "Tenho habilidade para comunicar a outros as verdades da Palavra de Deus.",
  6: "Meu desejo é que todas as pessoas que encontro conheçam o Senhor Jesus.",
  7: "Outros me consideram uma pessoa alegre e encorajadora.",
  8: "Tenho habilidade para guiar e cuidar de um grupo de pessoas.",
  9: "Tenho facilidade em sentir a dor e o sofrimento dos outros.",
  10: "Eu compartilho com prazer aquilo que possui com outras pessoas.",
  11: "Tenho uma habilidade especial para fazer amigos e conhecer novas pessoas.",
  12: "Sei que Deus responde minhas orações de forma especial.",
  13: "Tenho facilidade em delegar tarefas a outros.",
  14: "Sinto prazer em ensinar sobre as doutrinas básicas da Bíblia.",
  15: "Consigo identificar quem está sofrendo ou abatido e ajudá-lo.",
  16: "Gosto de explicar a Palavra de Deus de forma clara e objetiva.",
  17: "Sinto grande desejo em compartilhar o evangelho com os outros.",
  18: "Sou uma pessoa otimista e gosto de encorajar os outros.",
  19: "Acho fácil motivar as pessoas a se unirem para realizar uma tarefa.",
  20: "Eu me compadeço dos outros, especialmente daqueles que estão sofrendo.",
  21: "Tenho facilidade em compartilhar meus recursos materiais com outros.",
  22: "Tenho grande prazer em receber pessoas em minha casa.",
  23: "Acredito que Deus responde as minhas orações.",
  24: "Tenho capacidade para coordenar as atividades de outras pessoas.",
  25: "Acredito que tenho o dom de ensinar.",
  26: "Consigo ajudar pessoas que estão passando por dificuldades emocionais.",
  27: "Sou capaz de transmitir verdades bíblicas de forma simples e clara.",
  28: "Gosto de falar com as pessoas sobre Jesus.",
  29: "Consigo animar e encorajar pessoas em situações difíceis.",
  30: "Tenho habilidade para liderar grupos e realizar projetos.",
  31: "Sinto profunda compaixão por aqueles que estão em necessidade.",
  32: "Sinto que Deus me usa para suprir as necessidades materiais de outras pessoas.",
  33: "Tenho facilidade em abrir meu lar para receber outras pessoas.",
  34: "Tenho fé de que Deus sempre proverá aquilo que necessito.",
  35: "Tenho facilidade em organizar atividades e pessoas.",
  36: "Tenho prazer em estudar a Bíblia e ensinar aos outros.",
  37: "Gosto de ajudar aqueles que estão em necessidade emocional.",
  38: "Sinto que Deus me chama para pregar e ensinar a Palavra de Deus.",
  39: "Sinto que sou chamado para compartilhar o evangelho com os outros.",
  40: "Consigo animar pessoas que estão passando por dificuldades.",
  41: "Sinto-me chamado para liderar e cuidar de outros.",
  42: "Sinto grande compaixão pelos outros.",
  43: "Gosto de ajudar financeiramente nas necessidades da igreja.",
  44: "Sinto prazer em receber pessoas em minha casa.",
  45: "Acredito que Deus responde de maneira especial às minhas orações.",
  46: "Tenho facilidade em coordenar e organizar grupos.",
  47: "Gosto de ensinar e explicar a Palavra de Deus.",
  48: "Tenho empatia pelas pessoas que estão sofrendo.",
  49: "Tenho facilidade em ensinar e comunicar verdades bíblicas.",
  50: "Sinto-me chamado para evangelizar os outros.",
  51: "Tenho um espírito encorajador e motivador.",
  52: "Tenho habilidade para liderar projetos e grupos.",
  53: "Tenho compaixão por aqueles que estão sofrendo e desejo ajudá-los.",
  54: "Procuro manter contatos para incentivar os outros no seu crescimento espiritual.",
  55: "Sinto-me a vontade em presidir reuniões ou grupos, e se eu consigo conduzir os participantes num ambiente fraternal, de tal forma que, em geral mantenham em vista os alvos a serem atingidos.",
  56: "Posso me compadecer dos sentimentos daquele que passa por infortúnio, espontaneamente oferecer conforto prático.",
  57: "Na minha opinião, abrir concessões, dentro daquilo que se crê ser certo ou errado é quase sempre um erro; vejo as coisas em preto e branco, raramente em meio termo.",
  58: "Procuro contribuir para o trabalho do Senhor sem aqueles ao meu redor tomarem conhecimento.",
  59: "Quando vejo alguém precisando de algo que tenho condições de fazer ou de dar, minha tendência é me oferecer de imediato.",
  60: "Aguardo nos bastidores até alguém na direção me entregar a responsabilidade de fazer ou organizar os planos de um projeto.",
  61: "Gosto tanto de compartilhar o evangelho com não crentes, e contá-los de minha experiência com Cristo, que faço isto espontaneamente no ônibus, no serviço, em visitas de casa em casa, etc. e com meu coração transbordando de alegria.",
  62: "Levo muito a sério os pedidos de oração que vem ao meu conhecimento.",
  63: "Tenho interesses nos crentes que estão longe de seus familiares e quero que estes sintam que meu lar e minha família são deles.",
  64: "Gosto de ajudar os outros com suas tarefas, uma vez que eu tenha experiência em fazer aquilo, ou receba orientação.",
  65: "Gosto de me relacionar com um ou mais novo convertido discipulando-os para ajudá-los a caminhar, a crescer na fé, dar apoio, ir atrás deles quando se desviarem do caminho e/ou se ausentar da comunhão de outros crentes.",
  66: "Quando falo de uma verdade de Deus, minha tendência é ir além e mostrar aos outros que essa é uma verdade que funciona na prática.",
  67: "Acho que vale a pena compartilhar minhas experiências como Jesus me exortou, me corrigiu, me abençoou, para ajudar a animar e incentivar alguém que passa por problemas ou situação semelhante.",
  68: "Tenho boa experiência em persuadir outros a se encaminharem juntamente comigo para alcançar objetivos cristãos, tais como: aprender a viver o amor cristão de verdade; exercer seus dons espirituais; estabelecer e manter um trabalho beneficente para pobres, etc.",
  69: "Eu me sinto mal quando alguém fala ou faz alguma coisa que fere um outro emocionalmente.",
  70: "Sou persuasivo falando com outras pessoas.",
  71: "Procuro cuidar muito bem do dinheiro em minhas mãos para poder dar liberal e generosamente ao trabalho de Deus.",
  72: "É fácil eu me lembrar das preferências (os “eu gosto” e os “eu não gosto”) das pessoas do meu círculo de relacionamento.",
  73: "Minha cabeça está cheia de ideias, e gosto de bolar planos para meu grupo realizar um objetivo, dando oportunidade para o exercício de talentos natos e de dons espirituais, planejando em detalhes a sequência daquilo que tem de ser feito. O uso dos recursos materiais e do tempo disponíveis é acompanhado juntamente com a realização dos planos.",
  74: "Quando falo de Cristo com alguém, não estou satisfeito em parar ali, mas quero conduzir esta pessoa aos pés de Cristo e vê-la arrebanhada com outras ovelhas, sendo alimentada numa igreja.",
  75: "Identifico-me com os irmãos que sofrem perseguição pela fé, procuro ficar a par da situação deles para orar inteligentemente e com frequência a favor deles e a favor de seus perseguidores.",
  76: "Eu me sentiria participante do ministério de evangelização, abrindo meu lar para um irmão, dotado por Deus, dirigir estudos bíblicos para gente interessada no evangelho.",
  77: "Tenho vontade de facilitar as coisas para irmãos fisicamente fracos, especialmente para eles poderem participar de alguma maneira no corpo de Cristo, exercendo seus dons espirituais e sentindo-se úteis e felizes.",
  78: "Tem sido agradável para mim ter a responsabilidade de promover o bem espiritual de um grupo de crentes.",
  79: "Tenho a tendência de questionar ou querer testar aquilo que outros me ensinam, e com o qual não concordo.",
  80: "Gosto de falar e me relacionar um a um com as pessoas mais do que falar para grupos.",
  81: "Para eu ter condições de ir à frente, guiando as ovelhas do Senhor em seus caminhos, estou disposto a me submeter ao Espírito Santo, custe o que custar, para que Ele transforme continuamente o meu ser e a minha imagem de Cristo.",
  82: "Quando, durante o culto, o ambiente não emana uma verdadeira comunhão entre os irmãos, ou, pelo contrário, quando há um ambiente receptivo, eu posso perceber isto rapidamente.",
  83: "Sinto-me impelido a falar aquilo que penso sobre as coisas de Deus.",
  84: "Tenho facilidade em reconhecer necessidades financeiras no trabalho de Deus, que os outros demoram para enxergar ou nunca percebem.",
  85: "Sinto-me frustrado quando uma tarefa tem de ser completada até certa hora ou data.",
  86: "Gosto de pesquisar detalhes de um assunto, e não apenas estudá-lo por alto.",
  87: "Tenho experiência feliz em ajudar outros que têm problemas pessoais.",
  88: "Tenho influenciado outros a participarem em conjunto de determinada tarefa, ou em prosseguir em direção a um alvo ou objetivo cristão, vendo bons resultados posteriormente.",
  89: "Gosto (ou gostaria) de fazer visitas em hospitais, em orfanatos ou lares para velhos, ou talvez em presídios; penso que tenho algo a oferecer nesse tipo de ministério.",
  90: "Sou visto, às vezes, como pessoa antipática na igreja ou comunidades, porque fico preocupado com os erros dos outros e falo logo.",
  91: "Tenho satisfação em motivar outros a contribuírem para o trabalho do Senhor.",
  92: "Quando aquilo que faço, procurando suprir uma necessidade, não é apreciado, sinto-me decepcionado.",
  93: "Sou motivado a explicar verdades bíblicas.",
  94: "Creio que o testemunho de uma vida verdadeiramente cristã fala alto, senão mais alto, do que o testemunho verbal.",
  95: "Gosto de completar cada tarefa ou trabalho o mais rapidamente possível.",
  96: "Posso me aproximar e me identificar com aqueles que estão passando por problemas espirituais e/ou emocionais.",
  97: "Gosto mais de falar as verdades de Deus a grupos do que a indivíduos.",
  98: "Tenho a capacidade de fazer compras e investimentos de maneira sábia e equilibrada.",
  99: "Sou uma pessoa que facilmente sente afeição genuína pelos outros.",
  100:
      "Gosto de separar um tempo considerável para aprender a me aprofundar em verdades bíblicas, para comunicá-las aos outros.",
  101:
      "Sinto-me frustrado quando aquele que me ensina a palavra de Deus deixa de indicar alguns passos que se devem seguir para aplicar aquela verdade na vida da gente.",
  102:
      "Gosto de achar e aceitar um novo desafio quando um bem sucedido trabalho meu se encerra ou é confiado a outros capacitados.",
  103: "Minha tendência é me fechar às pessoas insensíveis ou insinceras.",
  104:
      "Tenho a tendência de ser brusco demais quando eu me expresso aos outros.",
  105:
      "Parece que tenho facilidade em adquirir ou ganhar dinheiro, e ao mesmo tempo, tenho uma forte atração pela obra de Deus, onde há necessidades financeiras que posso suprir.",
  106:
      "Posso gastar horas fazendo alguma coisa que beneficie direta e imediatamente aos outros, sem me preocupar com o cansaço."
};
